config/routes.rb
Rails.application.routes.draw do

  resources :books do 
    member do 
      put "donate"
    end
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'books#index'

    get "about" => "pages#about"
    get "contact" => "pages#contact"
    get "features" => "pages#features"
    get "home" => "books#index"
    get "profile" => "pages#profile"

    get "pricing" => "pages#pricing"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
    # Anonymous User
    can [:read], Book

    # Logged in
    if user 

      can [:create], Book
      can [:update, :destroy], Book do |book| 
        user == book.user 
      end
    end
 

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	belongs_to :donee, foreign_key: "donee_id", class_name: :User

	
	has_attached_file :image, :style => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	def donated?
		self.donee
	end

	def donated_to? (user)
		donee_id == user.id
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

 def set_locale
  logger.debug "* Accept-Language: #{request.env['HTTP_ACCEPT_LANGUAGE']}"
  I18n.locale = extract_locale_from_accept_language_header
  logger.debug "* Locale set to '#{I18n.locale}'"
 end
 
private
  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource only: :donate
  before_action :authenticate_user!, except: :index

  # GET /books
  # GET /books.json
  def index

    if current_user.present?
      if params[:donor]  == current_user.id.to_s
        @books = @books.select{ |b| b.user == current_user}
      elsif params[:donee] == current_user.id.to_s
        @books = @books.select{ |b| b.donee == current_user}
      else
        @books = Book.all.reject{ |b| b.donated_to? current_user}
      end
    else
      Book.all
    end

    # @books = @books.select { |b| 
    #   b.donee_id==user.id
    # }
  end

  # GET /books/1
  # GET /books/1.json
  def show

  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def donate
    @book.donee = current_user
    @book.donated_at = Time.now

    if @book.save && ( @book.donated_to? current_user )
      redirect_to action: "index"
      flash[:notice] = "book successfully donated to you!"
    else
      redirect_to @book
      flash[:error] = "Oh no! You can't receive this book"
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :isbn, :image, :age, :description, :subject)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def profile
    @user = current_user
    @received = Book.where(donee: current_user)
    @donated = Book.where(user: current_user)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :age, :gender, :email, :password, :password_confirmation, :home_address)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :age, :gender, :email, :password, :password_confirmation, :current_password, :home_address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="item">
  <div class="animate-box">

    <a href="<%= book_path(book)%>" class="fh5co-board-img"> <%= image_tag book.image.url %></a>
    <div class="fh5co-desc">
      <div><%= book.name %> <%= "(#{book.subject})" if book.subject.present? %></div>
      <%= link_to (t 'donate'), donate_book_path(book), method: :put unless book.donated? %>

      <% unless local_assigns[:hide_edit] %>
        <%= link_to (t 'edit'), edit_book_path(book) if (can? :update, book) %>
        <%= link_to (t 'destroy'), book, method: :delete, data: { confirm: 'Are you sure?' } if (can? :destroy, book)%>
      <% end %>
    </div>

  </div>
</div>

app/views/books/_form.html.erb
<%= form_for @book, html: { multipart: true } do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :time_of_book_being_used %><br>
    <%= f.text_field :age %><div>year(s)</div>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div id="fh5co-main">
  <div class="container">

    <div class="row">

      <% if user_signed_in? %>
        <%= link_to (t 'nb'), new_book_path, class: "btn btn‐primary btn‐lg" %>
      <% else %>
        <%= link_to "#{t 'login'}", new_user_session_path, class: "btn btn‐primary btn‐lg" %>
    <% end %>

    </div>

    <div class="row">

      <div id="fh5co-board" data-columns>

        <%= render partial: :book, collection: @books, locals: { hide_edit: true } %>

      </div>

    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div id="fh5co-main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2> <%= @book.name %> </h2>
        <div class="fh5co-spacer fh5co-spacer-sm"></div>
        <p>
          <%= image_tag @book.image.url, class: "img-rounded img-responsive" %>
        </p>

        <p>
          <strong>ISBN(<%= t('isbn'); %>):</strong>
          <%= @book.isbn %>
        </p>

        <p>
          <strong><%= t('age'); %>:</strong>
          <%= @book.age %>
        </p>

        <p>
          <strong><%= t('subject'); %>:</strong>
          <%= @book.subject %>
        </p>

        <p>
          <strong><%= t('des'); %>:</strong>
          <%= @book.description %>
        </p>

        <%= link_to (t 'donate'), donate_book_path(@book), method: :put unless @book.donated? %> |
        <%= link_to (t 'edit'), edit_book_path(@book) if (can? :update, @book)%> |
        <%= link_to (t 'back'), books_path %>


      </div>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="fh5co-footer">

  <div class="container">
    <div class="row row-padded">
      <div class="col-md-12 text-center">
        <!--<p class="fh5co-social-icons">-->
          <!--<a href="#"><i class="icon-twitter"></i></a>-->
          <!--<a href="#"><i class="icon-facebook"></i></a>-->
          <!--<a href="#"><i class="icon-instagram"></i></a>-->
          <!--<a href="#"><i class="icon-dribbble"></i></a>-->
          <!--<a href="#"><i class="icon-youtube"></i></a>-->
        <!--</p>-->
        <p><small>&copy; All Rights Reserved. </small></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Bookdonation", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "#{t 'home'}", root_path %></li>
        <li><a href="/about"><%= t('about'); %></a></li>
        <li><a href="/books"><%= t('book'); %></a></li>
        <li><a href="/pricing"><%= t('pricing'); %></a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
            <% if user_signed_in? %>
                <%= link_to("#{t 'My donations'}", books_path(donor: current_user.id), 
                  class: "btn btn‐primary btn‐lg") %>
                <%= link_to("#{t 'My received books'}", books_path(donee: current_user.id), 
                  class: "btn btn‐primary btn‐lg") %>
                <%= link_to("#{t 'Logout'}", destroy_user_session_path, :method => :delete, 
                  class: "btn btn‐primary btn‐lg") %>

            <% else %>
              <p>
                   <%= link_to "#{t 'login'}", new_user_session_path, class: "btn btn‐primary btn‐lg" %>
                   <%= link_to "#{t 'signup'}", new_user_registration_path, class: "btn btn‐primary btn‐lg" %>
              </p>
            <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_top.html.erb
<div id="fh5co-offcanvass">
  <a href="#" class="fh5co-offcanvass-close js-fh5co-offcanvass-close">Menu <i class="icon-cross"></i> </a>
  <h1 class="fh5co-logo"><a class="navbar-brand" href="/home">Book Donation</a></h1>
  <ul>
    <li class="active"><a href="/">Home</a></li>
    <li><a href="/about.html">About</a></li>
    <li><a href="/features.html"><%= t('wd') %></a></li>
    <li><a href="/contact.html">Contact</a></li>
    <% if current_user.present?%>
      <li><a href="/profile.html">Profile</a></li>
      <li><%= link_to "#{t 'logout'}", destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to "#{t 'login'}", new_user_session_path %></li>
    <% end %>

  </ul>
  <!--<h3 class="fh5co-lead">Connect with us</h3>-->
  <!--<p class="fh5co-social-icons">-->
    <!--<a href="#"><i class="icon-twitter"></i></a>-->
    <!--<a href="#"><i class="icon-facebook"></i></a>-->
    <!--<a href="#"><i class="icon-instagram"></i></a>-->
    <!--<a href="#"><i class="icon-dribbble"></i></a>-->
    <!--<a href="#"><i class="icon-youtube"></i></a>-->
  <!--</p>-->
</div>

<header id="fh5co-header" role="banner">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <a href="#" class="fh5co-menu-btn js-fh5co-menu-btn">Menu <i class="icon-menu"></i></a>
        <a class="navbar-brand" href="/home">Book Donation</a>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <link rel="shortcut icon" href="favicon.ico">

  <!--google webfonts-->
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>


  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Donation of books" />
  <meta name="keywords" content="book donation schools charity library nonprofit" />

</head>
<body>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class:"alert alert-info") %>
  <% end %>
</div>
	<%= render 'layouts/top' %>


	
	<%= yield %>

  <%= render 'layouts/footer' %>

  <%= javascript_include_tag 'application' %>

</body>
</html>

app/views/pages/about.html.erb
<div id="fh5co-main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2><%= t('about us'); %></h2>
        <div class="fh5co-spacer fh5co-spacer-sm"></div>
        <p>
          <img src="images/school.jpg" alt="Kimi's School" class="img-rounded img-responsive"></p>

        <p><%= t('about detail'); %></p>

      </div>

    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div id="fh5co-main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2>Contact</h2>
        <div class="fh5co-spacer fh5co-spacer-sm"></div>
        <form action="#">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="First Name">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Last Name">
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <input type="email" class="form-control" placeholder="Email Address">
              </div>
              <div class="form-group">
                <textarea name="message" id="message" cols="30" class="form-control" rows="10"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Send Message">
              </div>
            </div>
          </div>
        </form>

      </div>

    </div>
  </div>
</div>

app/views/pages/features.html.erb
<div id="fh5co-main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2><%= t("wd") %></h2>
        <div class="fh5co-spacer fh5co-spacer-sm"></div>
        <div class="row">
          <div class="col-md-4">
            <div class="fh5co-pricing-table">
              <h3><%= t('school'); %></h3>
              <ul class="fh5co-list-check">
                <li class="fh5co-include"><%= t('s1'); %></li>
                <li class="fh5co-include"><%= t('s2'); %></li>
				        <li class="fh5co-include"><%= t('s3'); %></li>
              </ul>
              <a href="#" class="btn btn-block btn-sm btn-outline">Sign up</a>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fh5co-pricing-table">
              <h3><%= t('personal'); %></h3>
              <ul class="fh5co-list-check">
                <li class="fh5co-include"><%= t('p1'); %></li>
                <li class="fh5co-include"><%= t('p2'); %></li>
                <li class="fh5co-include"><%= t('p3'); %></li>
              </ul>
              <a href="#" class="btn btn-block btn-sm btn-primary">Sign up</a>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fh5co-pricing-table">
              <h3><%= t('organization'); %></h3>
              <ul class="fh5co-list-check">
                <li class="fh5co-include"><%= t('o1'); %></li>
                <li class="fh5co-include"><%= t('o2'); %></li>
                <li class="fh5co-include"><%= t('o3'); %></li>
              </ul>
              <a href="#" class="btn btn-block btn-sm btn-outline">Sign up</a>
            </div>
          </div>
        </div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Book Donation</h1>
	<p><%= t('intro'); %></p>      
</div>

app/views/pages/pricing.html.erb
<div id="fh5co-main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2><%= t("wd") %></h2>
        <div class="fh5co-spacer fh5co-spacer-sm"></div>
        <div class="row">
          <div class="col-md-4">
            <div class="fh5co-pricing-table">
              <h3><%= t('school'); %></h3>
              <ul class="fh5co-list-check">
                <li class="fh5co-include"><%= t('s1'); %></li>
                <li class="fh5co-include"><%= t('s2'); %></li>
				        <li class="fh5co-include"><%= t('s3'); %></li>
              </ul>
              <a href="#" class="btn btn-block btn-sm btn-outline">Sign up</a>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fh5co-pricing-table">
              <h3><%= t('personal'); %></h3>
              <ul class="fh5co-list-check">
                <li class="fh5co-include"><%= t('p1'); %></li>
                <li class="fh5co-include"><%= t('p2'); %></li>
                <li class="fh5co-include"><%= t('p3'); %></li>
              </ul>
              <a href="#" class="btn btn-block btn-sm btn-primary">Sign up</a>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fh5co-pricing-table">
              <h3><%= t('organization'); %></h3>
              <ul class="fh5co-list-check">
                <li class="fh5co-include"><%= t('o1'); %></li>
                <li class="fh5co-include"><%= t('o2'); %></li>
                <li class="fh5co-include"><%= t('o3'); %></li>
              </ul>
              <a href="#" class="btn btn-block btn-sm btn-outline">Sign up</a>
            </div>
          </div>
        </div>

app/views/pages/profile.html.erb
<div id="fh5co-main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2><%=@user.email %></h2>
        <div class="fh5co-spacer fh5co-spacer-sm"></div>
        <p>
        </p>

        <p><%= t('first n'); %>: <%= @user.first_name %></p>
        <p><%= t('last n'); %>: <%= @user.last_name %></p>
        <p><%= t('ages'); %>: <%= @user.age %></p>
        <p><%= t('gender'); %>: <%= @user.gender %></p>
        <p><%= t('home address'); %>: <%= @user.home_address %></p>

        <div class="row">

          <h2>Donated Books</h2>

          <div id="fh5co-board" data-columns>

            <% @donated.each do |book| %>
              <%= render book %>
            <% end %>

          </div>
        </div>

        <div class="row">

          <h2>Received Books</h2>

          <div id="fh5co-board" data-columns>

            <% @received.each do |book| %>
              <%= render book %>
            <% end %>

          </div>


        </div>

      </div>


    </div>
  </div>
</div>